name: CI
on:
  push:
    branches: [ main, develop, "feat/**", "fix/**" ]
  pull_request:
    branches: [ main, develop ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if test -f requirements.txt; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov

      - name: Run tests
        run: |
          pytest --cov=src --cov-report=term-missing
